module.exports = { 
    securityCode: "launchpad",
    SUPERADMIN: "SUPERADMIN",
    SUBADMIN: "SUBADMIN",
    USER: "USER",
    RES_STATUS_SUCCESS: 1,
	RES_STATUS_FAIL: 0,
	RES_STATUS_EXIST: 2,
	RES_MSG_SAVE_SUCCESS: "Data is saved successfuly",
	RES_MSG_SAVE_FAIL: "Data saving is fail",
	RES_MSG_UPDATE_SUCCESS: "Data is updated successfuly",
	RES_MSG_UPDATE_FAIL: "Data updating is fail",
	RES_MSG_DELETE_SUCCESS: "Data is deleted successfuly",
	RES_MSG_DELETE_FAIL: "Data deletion is fail",
	RES_MSG_DATA_NOT_FOUND: "Data is not found",
	RES_MSG_DATA_FOUND: "Data is found",
	RES_MSG_SUCESS: "Success",
	RES_MSG_FAIL: "Failure",
	RES_MSG_INVALID_REQUEST: "Invalid request",
    PERCENT_DIVISOR: 1000,
    TX_TYPE_DEPOSIT: "DEPOSIT",
    TX_TYPE_LOCK: "LOCK",
    TX_TYPE_WITHDRAW: "WITHDRAW",
    TX_TYPE_SWAP: "SWAP",
    TX_TYPE_REFUND: "REFUND",
    TX_TYPE_BUY_IGO: "BUY_IGO",
    TX_TYPE_CLAIM_IGO: "CLAIM_IGO",
    TX_STATUS_SUCCESS: "SUCCESS",
    TX_STATUS_FAIL: "FAIL",
    USER_STATUS_PENDING: 0,
    USER_STATUS_APPROVE: 1,
    USER_STATUS_SUSPEND: 2,
}